:hardbreaks:
= 도전과제, 발전과제 advancements

== Caves and Cliffs 동굴과 절벽
https://www.youtube.com/watch?v=cu0Bsu2Z_eg

== 별 상인 Star Trader 최고의 거래
https://www.youtube.com/watch?v=l7ZbbEcjDus

크레이티브모드에서도 되는건가...

== 사운드 오브 뮤직

== 고향 같은 편안함

== 우정의 치유력!

== 좋을 대로 해

== 왁스 칠, 왁스 제거

== 오오, 반짝반짝!

== 잔해로 뒤덮기

== 명중

== 끈적한 상황

== 벌들의 이주

== 벌청객

== 스튜의 시간

== 경보 발동!

== 공격당한다!

== 싸게 사서 비싸게 팔기

== 야수 처치!

== 고양이투성이

== 베틀 위의 과일

== 어디 있었어?

== 세계의 정상

== 동물학자

== 초음파 탐지

== 일곱 바다 항해하기
모든 바다 바이옴을 방문하세요.

== 보물 사냥꾼
지도 제작자 주민에게서 지도를 획득해 표시된 건물에 입장하세요.

== 꼼꼼한 마법사
모루에서 셜커 상자에 이름을 부여하세요,

== 얼음의 요정!
차가운 걸음 효과가 부여된 부츠를 신고 깊은 바다에서 얼어 있는 수면위를 1블록 이상 이동하세요.

== 서우치감은 자기 만족
5마리 이상의 라마가 포함된 캐러밴을 끌고 이동하세요.

== 양치 좀 해라
유리병에 드래곤의 숨결을 담으세요.

== 초음파
딱지날개를 사용해 초당 40m 이상의 속도로 이동하면서 1x1 틈새위로 뛰어넘으세요.

== 죽여주는 경치
셜커의 공격을 받고 블록 50개 이상 높이로 떠오르세요.

== 또 다시... 끝...
엔더 드래곤을 재생성하세요,

== 끝이야.
엔더 드래곤을 처치하십시오.

== 이걸로 끝이야?
엔더 포탈에 들어가십시오.

== 시작이야.
위더를 죽이세요.

== 신호기 제작자
신호기를 제작해 가장 세게 활성화하세요

== 시작이야?
위더를 생성하세요

== 압도적인 힘
효과부여 사과를 먹으세요

== 인공 선택
말과 당나귀를 교배시켜 노새를 만드십시오.

== 인셉션
피스톤을 다른 피스톤으로 누른 후, 원래 피스톤이 다른 피스톤을 밀어내도록 하십시오.

== 돼지. 날다
안장을 이용해서 돼지를 탄 후, 절벽에서 떨어지십시오.

== 홀치기 염색 의상
가마솥을 사용해서 4가지 고유 부위의 가죽 갑옷을 염색하십시오.

== 좀비 의사
좀비 주민 한 명을 치료하십시오.

== 네 약 맛이 어때?
투척용 포션으로 마녀를 중독시키십시오.

== 저격 대결
50m 이상 거리에서 화살 한 발로 스켈레톤 하나를 처치하십시오.

== 멋진 화분
화분을 하나 만들어서 놓으십시오.

== 지도실
완전히 탐사된 인접지역 지도 9장을 3x3 배열의 아이템 액자 9개에 넣으십시오.

== 위장
종류가 같은 몹 머리를 착용한 상태에서 몹을 처치하십시오.
